### ISSUE TITLE
About The GuidedUSCal

### ISSUE THREAD

**Issue by yogeren** [VASST/SlicerVASST#15]
Hi~Mr Rankin:
      I have learnt your tutorial about Slicer Python Module Creation and Setting up python debugging in Slicer. It's useful! I want to create the module of the "GuidedUSCal", have you recorded some tutorials about How to use the "GuidedUSCal"？
      Thanks, all the best!

**Comment by adamrankin** [comment]
No sorry, this module was written by someone else. Most likely you'll need an ultrasound machine, a tracker, and a Plus setup streaming into Slicer's openigtlink. You'll find similar helpful tutorials here

http://www.slicerigt.org/wp/user-tutorial/
