### ISSUE TITLE
Can I link the ramps1.4 PCB based on Marlin which is used in 3d printer usually with SlicerVASST?

### ISSUE THREAD

**Issue by timeanddoctor** [VASST/SlicerVASST#6]
Can I link the ramps1.4 PCB based on Marlin which is used in 3d printer usually with SlicerVASST?

**Comment by adamrankin** [comment]
This fork of marlin is customized for a IdeaBuilder 20 with MKS Base 1.5 retrofit. I recommend you check out the Marlin community for guides to customizing for your printer.
